blogs/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'blogs'
urlpatterns = [
    path('', views.BlogsView.as_view(), name='all'),
    path('blog/<str:slug>', views.BlogView.as_view(), name='blog'),
    path('edit', views.EditView.as_view(), name='edit'),
    path('blog/create/', views.BlogCreate.as_view(), name='blog_create'),
    path('blog/<int:pk>/update/', views.BlogUpdate.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', views.BlogDelete.as_view(), name='blog_delete'),
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
    path('authors/', views.AuthorView.as_view(), name='author_list'),
]

# path('', views.MainView.as_view(), name='all'),
# path('main/create/', views.AutoCreate.as_view(), name='auto_create'),
# path('main/<int:pk>/update/', views.AutoUpdate.as_view(), name='auto_update'),
# path('main/<int:pk>/delete/', views.AutoDelete.as_view(), name='auto_delete'),
# path('lookup/', views.MakeView.as_view(), name='make_list'),
# path('lookup/create/', views.MakeCreate.as_view(), name='make_create'),
# path('lookup/<int:pk>/update/', views.MakeUpdate.as_view(), name='make_update'),
# path('lookup/<int:pk>/delete/', views.MakeDelete.as_view(), name='make_delete'),

blogs/models.py
from django.db import models
from django.core.validators import MinLengthValidator


class Author(models.Model):
    name = models.CharField(
        max_length=100,
        help_text='Enter your name',
        validators=[MinLengthValidator(2, "Author name must be greater than 1 character")]
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Blog(models.Model):
    sno = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    content = models.TextField()
    slug = models.CharField(max_length=100)
    trailer = models.CharField(max_length=300, null=True)
    time = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey('Author', on_delete=models.CASCADE, null=False)

    # Shows up in the admin list
    def __str__(self):
        return self.title

home/models.py
from django.db import models

# Create your models here.

blogs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from blogs.models import Author, Blog


# Create your views here.
class BlogsView(View):
    def get(self, request):
        ac = Author.objects.all().count()
        bl = Blog.objects.all()
        ctx = {'author_count': ac, 'blogs_list': bl}
        return render(request, 'blogs/blogs.html', ctx)


class EditView(LoginRequiredMixin, View):
    def get(self, request):
        ac = Author.objects.all().count()
        bl = Blog.objects.all()
        ctx = {'author_count': ac, 'blogs_list': bl}
        return render(request, 'blogs/edit_blog_list.html', ctx)


class BlogView(View):
    def get(self, request,  *args, **kwargs):
        slug = kwargs['slug']
        b = Blog.objects.filter(slug=slug).first()
        ctx = {'blog': b}
        return render(request, 'blogs/blog.html', ctx)


class BlogCreate(LoginRequiredMixin, CreateView):
    model = Blog
    fields = '__all__'
    success_url = reverse_lazy('blogs:all')


class BlogUpdate(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = '__all__'
    success_url = reverse_lazy('blogs:all')


class BlogDelete(LoginRequiredMixin, DeleteView):
    model = Blog
    fields = '__all__'
    success_url = reverse_lazy('blogs:all')


class AuthorUpdate(LoginRequiredMixin, UpdateView):
    model = Author
    fields = '__all__'
    success_url = reverse_lazy('blogs:all')


class AuthorDelete(LoginRequiredMixin, DeleteView):
    model = Author
    fields = '__all__'
    success_url = reverse_lazy('blogs:all')


class AuthorCreate(LoginRequiredMixin, CreateView):
    model = Author
    fields = '__all__'
    success_url = reverse_lazy('blogs:all')


class AuthorView(LoginRequiredMixin, View):
    def get(self, request):
        al = Author.objects.all()
        ctx = {'author_list': al}
        return render(request, 'blogs/author_list.html', ctx)

home/views.py
from django.shortcuts import render

# Create your views here.

blogs/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
    {% block js %}{% endblock%}
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/">Prajwol's Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item {% block home_active %}{% endblock home_active %}">
            <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item {% block blog_active %}{% endblock blog_active %}">
            <a class="nav-link" href="/blogs">Blog<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item {% block edit_active %}{% endblock edit_active %}">
            <a class="nav-link" href="/blogs/edit">Edit<span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <form action="/search" method="get" class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    {% block body %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

blogs/templates/blogs/author_confirm_delete.html
{% extends "base.html" %}

{% block body %}

<h1>Delete Make</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'blogs:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

blogs/templates/blogs/author_form.html
{% extends "base.html" %}

{% block body %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'blogs:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

blogs/templates/blogs/author_list.html
{% extends "base.html" %}

{% block body %}
  <h1>Author List</h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
      <li>
          {{ author.name }}
         (<a href="{% url 'blogs:author_update' author.id %}">Update</a> |
          <a href="{% url 'blogs:author_delete' author.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no authors in your blog.</p>
  {% endif %}
  <p><a href="{% url 'blogs:author_create' %}">Add an author</a></p>
  <p>
    <a href="{% url 'blogs:all' %}">Back to blogs</a>
  </p>
{% endblock %}

blogs/templates/blogs/blog.html
{% extends "base.html" %}
{% block title %}Blog{% endblock %}
{% block blog_active %}active{% endblock blog_active %}
{% block body %}
    <div class="my-3 mx-4">
        <h1>{{ blog.title }}</h1>
        <h3>{{ blog.author }}</h3>
        <p>{{ blog.content|safe }}</p>
    </div>
{% endblock %}

blogs/templates/blogs/blog_confirm_delete.html
{% extends "base.html" %}

{% block body %}

<h1>Delete Blog</h1>

<p>Are you sure you want to delete the blog: {{ blog }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

blogs/templates/blogs/blog_form.html
{% extends "base.html" %}


{% block body %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'blogs:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

blogs/templates/blogs/blogs.html
{% extends "base.html" %}
{% block title %}Blogs{% endblock %}
{% block blog_active %}active{% endblock blog_active %}
{% block body %}
    <div class="container">
        {% if blogs_list %}
            {% for blog in blogs_list %}
            <div class="my-4">
                <h3 class="text-dark"><a href="/blogs/blog/{{blog.slug}}"" class="text-dark my-3">{{blog.title}}</a></h3>
                <div class="my-2">
                    {{blog.trailer|slice:245}}...
                </div>
                <a href="/blogs/blog/{{blog.slug}}" class="btn btn-primary btn-sm active" role="button" aria-pressed="true">Read More</a>
                <br/>
                <br/>
            </div>
            {% endfor %}
        {% else %}
            <p>There are no blogs.</p>
        {% endif %}
    </div>
{% endblock %}

blogs/templates/blogs/edit_blog_list.html
{% extends "base.html" %}
{% block title %}Edit{% endblock %}
{% block edit_active %}active{% endblock edit_active %}
{% block body %}
    <h3 class="my-3 mx-3">Welcome to Blog List</h3>
    {% if blogs_list %}
        <ul>
        {% for blog in blogs_list %}
            <li>
                {{ blog.title }} ({{ blog.author }})
                (<a href="{% url 'blogs:blog_update' blog.sno %}">Update</a> |
                <a href="{% url 'blogs:blog_delete' blog.sno %}">Delete</a>) <br/>
                {{ blog.trailer }}
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>There are no blogs.</p>
    {% endif %}
    <p>
        {% if author_count > 0 %}
            <a href="{% url 'blogs:blog_create' %}">Add a blog</a>
        {% else %}
            Please create an author before you add a blog.
        {% endif %}
    </p>
    <p>
        <a href="{% url 'blogs:author_list' %}">View Authors</a> ({{ author_count }}) |
        <a href="{% url 'blogs:author_create' %}">Add an Author</a>
    </p>
{% endblock %}

home/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<!-- Replace this value (42-42) with the one provided by the autograder -->
<meta name="dj4e" content="42-42">

<meta name="dj4e-code" content="99999999">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<meta name="dj4e-version" content="2021-04-14">

{% block head %} {% endblock %}

</head>
<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

home/templates/home/main.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Home</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/">Prajwol's Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item {% block blog_active %}{% endblock blog_active %}">
            <a class="nav-link" href="/blogs">Blog<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item {% block edit_active %}{% endblock edit_active %}">
            <a class="nav-link" href="/blogs/edit">Edit<span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <form action="/search" method="get" class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <h1 class="my-3">Hello Welcome to my application</h1>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>